export type Team = 'startup' | 'investing';

export interface TeamMember {
  name: string;
  team: Team;
}

export interface SemesterData {
  semester: 'spring' | 'fall';
  year: number;
  members: TeamMember[];
}

export const teamsData: SemesterData[] = [
  {
    semester: 'fall',
    year: 2025,
    members: [
      { name: 'Mihir Ganesan', team: 'startup' },
      { name: 'Katherine Graci', team: 'startup' },
      { name: 'Jessie Lee', team: 'startup' },
      { name: 'Maggie Lu', team: 'startup' },
      { name: 'Surya Newa', team: 'startup' },
      { name: 'Pranav Sarma', team: 'startup' },
      { name: 'Xander Wanagel', team: 'startup' },
      { name: 'Anup Banerjee', team: 'investing' },
      { name: 'Mitch Cahill', team: 'investing' },
      { name: 'Neel Khurana', team: 'investing' },
      { name: 'Shray Patel', team: 'investing' },
      { name: 'Eric Tao', team: 'investing' },
      { name: 'Priscilla Tu', team: 'investing' },
    ],
  },
  {
    semester: 'spring',
    year: 2025,
    members: [
      { name: 'Andi Jegeni', team: 'startup' },
      { name: 'Danny Konovalov', team: 'startup' },
      { name: 'Nihar Bagkar', team: 'startup' },
      { name: 'Zaara Israni', team: 'startup' },
      { name: 'Abhiviraj Goel', team: 'startup' },
      { name: 'Yvette Bu', team: 'startup' },
      { name: 'Suriya Gnanasundar', team: 'startup' },
      { name: 'Brian Dai', team: 'startup' },
      { name: 'Zachary Semple', team: 'investing' },
      { name: 'Yash Pandya', team: 'investing' },
      { name: 'Michael Que', team: 'investing' },
      { name: 'Ein Sel', team: 'investing' },
    ],
  },
  {
    semester: 'fall',
    year: 2024,
    members: [
      { name: 'Benedict Marco Kosasih', team: 'startup' },
      { name: 'Bhoomika Navandar', team: 'startup' },
      { name: 'Lia Kostas', team: 'startup' },
      { name: 'Rifa Gowani', team: 'startup' },
      { name: 'Ronak Vusirikala', team: 'startup' },
      { name: 'Soumya Medapati', team: 'startup' },
      { name: 'Ivan Silkin', team: 'investing' },
      { name: 'Jai Tamboli', team: 'investing' },
      { name: 'Nicole Hwang', team: 'investing' },
      { name: 'Sophia Chen', team: 'investing' },
    ],
  },
  {
    semester: 'spring',
    year: 2024,
    members: [
      { name: 'Brian Zhou', team: 'startup' },
      { name: 'Evan Hitchcock', team: 'startup' },
      { name: 'Evan Liu', team: 'startup' },
      { name: 'Andrew Dinasan', team: 'investing' },
      { name: 'Evan Tian', team: 'investing' },
      { name: 'Mikhail Bond', team: 'investing' },
    ],
  },
  {
    semester: 'fall',
    year: 2023,
    members: [
      { name: 'Dustin He', team: 'startup' },
      { name: 'Marianna Hincapie', team: 'startup' },
      { name: 'Paul Chan', team: 'startup' },
      { name: 'Zoë Applebaum', team: 'startup' },
      { name: 'Brielee Lu', team: 'investing' },
      { name: 'Fred Rohn', team: 'investing' },
      { name: 'Kailani Liu', team: 'investing' },
      { name: 'Sebastian Strässer', team: 'investing' },
    ],
  },
  {
    semester: 'spring',
    year: 2023,
    members: [
      { name: 'Ignacio Beangii', team: 'startup' },
      { name: 'Marcelo Barrera', team: 'startup' },
      { name: 'Sriya Chekuri', team: 'startup' },
      { name: 'Yangyang Lai', team: 'investing' },
      { name: 'Advait Abrol', team: 'investing' },
      { name: 'Augustine Breeze', team: 'investing' },
      { name: 'Jessica Yu', team: 'investing' },
      { name: 'Nathan Lee', team: 'investing' },
    ],
  },
  {
    semester: 'fall',
    year: 2022,
    members: [
      { name: 'Aditi Baghel', team: 'startup' },
      { name: 'Akshat Chavan Patil', team: 'startup' },
      { name: 'Bianca Ashar', team: 'startup' },
      { name: 'Kiran Kashyap', team: 'startup' },
      { name: 'Ishaan Poojari', team: 'startup' },
      { name: 'Tao Xie', team: 'startup' },
      { name: 'Sofia Ortiz', team: 'startup' },
      { name: 'Andrew Berube', team: 'startup' },
      { name: 'Deyan Kassev', team: 'investing' },
      { name: 'Duncan Scott', team: 'investing' },
      { name: 'Jess Wang', team: 'investing' },
      { name: 'Kathy Cao', team: 'investing' },
    ],
  },
  {
    semester: 'spring',
    year: 2022,
    members: [
      { name: 'Aditi Kanaujia', team: 'startup' },
      { name: 'Akshat Jain', team: 'startup' },
      { name: 'Amber Liang', team: 'startup' },
      { name: 'Amolak Kumar', team: 'startup' },
      { name: 'Ava Keresztes', team: 'startup' },
      { name: 'Justin Tong', team: 'startup' },
      { name: 'Kevin Pichardo-Cedillo', team: 'startup' },
      { name: 'Krish Bajaj', team: 'startup' },
      { name: 'Preetham Prince', team: 'startup' },
      { name: 'Rayna Shah', team: 'startup' },
      { name: 'Renee Wu', team: 'startup' },
      { name: 'Ayeeshi Champaneria', team: 'investing' },
      { name: 'Megan Li', team: 'investing' },
      { name: 'Michelle Ankunda', team: 'investing' },
      { name: 'Nathan Ju', team: 'investing' },
      { name: 'Niklas Ng', team: 'investing' },
      { name: 'Niyanth Thatta', team: 'investing' },
      { name: 'Orisa Thanajaro', team: 'investing' },
    ],
  },
  {
    semester: 'fall',
    year: 2021,
    members: [
      { name: 'Alex Talamonti', team: 'startup' },
      { name: 'Aneesh Kethini', team: 'startup' },
      { name: 'Kayln Kwan', team: 'startup' },
      { name: 'Koko Xu', team: 'startup' },
      { name: 'Michael Shen', team: 'startup' },
      { name: 'Rafed Abbassi', team: 'startup' },
      { name: 'Rishi Gowda', team: 'startup' },
      { name: 'Sparsh Kabra', team: 'startup' },
      { name: 'Alan Chen', team: 'investing' },
      { name: 'Brian Xiao', team: 'investing' },
      { name: 'David Towers', team: 'investing' },
      { name: 'Emily Wang', team: 'investing' },
      { name: 'James Austin', team: 'investing' },
      { name: 'Joseph Wang', team: 'investing' },
      { name: 'Justin Chen', team: 'investing' },
      { name: 'Nathan Chong', team: 'investing' },
      { name: 'Proby Shandilya', team: 'investing' },
      { name: 'Rachel Cheng', team: 'investing' },
      { name: 'Ronak Shah', team: 'investing' },
    ],
  },
];
