import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "./components/Footer";
import { Navbar } from "./components/Navbar";
import { Preloader } from "./components/Preloader";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const gothamMedium = localFont({
  src: "../public/fonts/Gotham Medium.otf",
  variable: "--font-gotham-medium",
  weight: "500",
});

const gothamBold = localFont({
  src: "../public/fonts/Gotham Bold.otf",
  variable: "--font-gotham-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${gothamMedium.variable} ${gothamBold.variable} ${inter.className} antialiased`}>
        <Preloader />
        <Navbar logo={<img src="/eeg-logo.svg" alt="EEG Logo" className="w-[100px]" />} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
